# Näillä voi API kutsuja manuaalisesti testata jos tarpeen

POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "room": "A1",
    "startTime": "2026-01-31T06:00:00Z",
    "endTime": "2026-01-31T10:00:00Z",
    "reservedBy": "Käyttäjä"
}

###

GET http://localhost:3000/api/reservations/rooms/A1

###

DELETE http://localhost:3000/api/reservations/id
